version: "3"
services:
  web:
    image: org.wachowiak/math-service-docker
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
  web-client:
    image: org.wachowiak/math-service-client-docker
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:81"
    networks:
      - webnet
networks:
  webnet: